#!/usr/bin/perl

package sfile_bw;

@dat=($day, $month, $year) = (localtime(time-86400))[3,4,5];

$t1=@dat[0];
$t2=@dat[1]+1;
$t3=@dat[2]+1900;
$t0=0;


if ( $t2 == 1 ) {$t2 = "Jan";}
if ( $t2 == 2 ) {$t2 = "Feb";}
if ( $t2 == 3 ) {$t2 = "Mar";}
if ( $t2 == 4 ) {$t2 = "Apr";}
if ( $t2 == 5 ) {$t2 = "May";}
if ( $t2 == 6 ) {$t2 = "Jun";}
if ( $t2 == 7 ) {$t2 = "Jul";}
if ( $t2 == 8 ) {$t2 = "Aug";}
if ( $t2 == 9 ) {$t2 = "Sep";}
if ( $t2 == 10 ) {$t2 = "Oct";}
if ( $t2 == 11 ) {$t2 = "Nov";}
if ( $t2 == 12 ) {$t2 = "Dec";}


if ( $t1 < 10 )
{
$tt=$t0.$t1;
}

else
{
$tt=$t1;
}

$truedat=join('-',$t3,$t2,$tt);
$avi=".avi";
$fn=$truedat.$avi;
$path="/video/penta/$fn";

1;
